konradtaller/config/routes.rb
Rails.application.routes.draw do
  resources :appoiments
  resources :consulting_rooms
  resources :doctors
  resources :professions
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

konradtaller/app/models/appoiment.rb
class Appoiment < ApplicationRecord

  validates_presence_of :begindate, :enddate
  
  validate :no_reservation_overlap
  belongs_to :consulting_room
  belongs_to :patient
  belongs_to :doctor
 



def no_reservation_overlap
  if (Appoiment.where("(? BETWEEN begindate AND enddate OR ? BETWEEN begindate AND enddate) AND patient_id = ? AND doctor_id = ?", self.begindate, self.enddate, self.patient, self.doctor).any?)
     errors.add(:enddate, 'it overlaps another reservation')
  end
end
end

konradtaller/app/controllers/appoiments_controller.rb
class AppoimentsController < ApplicationController
  before_action :set_appoiment, only: [:show, :edit, :update, :destroy]

  # GET /appoiments
  # GET /appoiments.json
  def index
    @appoiments = Appoiment.all
  end

  # GET /appoiments/1
  # GET /appoiments/1.json
  def show
  end

  # GET /appoiments/new
  def new
    @appoiment = Appoiment.new
  end

  # GET /appoiments/1/edit
  def edit
  end

  # POST /appoiments
  # POST /appoiments.json
  def create
    @appoiment = Appoiment.new(appoiment_params)

    respond_to do |format|
      if @appoiment.save
        format.html { redirect_to @appoiment, notice: 'Appoiment was successfully created.' }
        format.json { render :show, status: :created, location: @appoiment }
      else
        format.html { render :new }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appoiments/1
  # PATCH/PUT /appoiments/1.json
  def update
    respond_to do |format|
      if @appoiment.update(appoiment_params)
        format.html { redirect_to @appoiment, notice: 'Appoiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appoiment }
      else
        format.html { render :edit }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appoiments/1
  # DELETE /appoiments/1.json
  def destroy
    @appoiment.destroy
    respond_to do |format|
      format.html { redirect_to appoiments_url, notice: 'Appoiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appoiment
      @appoiment = Appoiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appoiment_params
      params.require(:appoiment).permit(:consulting_room_id, :patient_id, :doctor_id, :begindate, :enddate, :comment)
    end
end

konradtaller/app/helpers/appoiments_helper.rb
module AppoimentsHelper
end

konradtaller/app/views/appoiments/_form.html.erb
<%= form_with(model: appoiment, local: true) do |form| %>
  <% if appoiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appoiment.errors.count, "error") %> prohibited this appoiment from being saved:</h2>

      <ul>
        <% appoiment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :consulting_room_id %>
    <%= form.text_field :consulting_room_id %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.text_field :doctor_id %>
  </div>

  <div class="field">
    <%= form.label :begindate %>
    <%= form.datetime_select :begindate %>
  </div>

  <div class="field">
    <%= form.label :enddate %>
    <%= form.datetime_select :enddate %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

konradtaller/app/views/appoiments/edit.html.erb
<h1>Editing Appoiment</h1>

<%= render 'form', appoiment: @appoiment %>

<%= link_to 'Show', @appoiment %> |
<%= link_to 'Back', appoiments_path %>

konradtaller/app/views/appoiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appoiments</h1>

<table>
  <thead>
    <tr>
      <th>Consulting room</th>
      <th>Patient</th>
      <th>Doctor</th>
      <th>Begindate</th>
      <th>Enddate</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appoiments.each do |appoiment| %>
      <tr>
        <td><%= appoiment.consulting_room_id %></td>
        <td><%= appoiment.patient_id %></td>
        <td><%= appoiment.doctor_id %></td>
        <td><%= appoiment.begindate %></td>
        <td><%= appoiment.enddate %></td>
        <td><%= appoiment.comment %></td>
        <td><%= link_to 'Show', appoiment %></td>
        <td><%= link_to 'Edit', edit_appoiment_path(appoiment) %></td>
        <td><%= link_to 'Destroy', appoiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appoiment', new_appoiment_path %>

konradtaller/app/views/appoiments/new.html.erb
<h1>New Appoiment</h1>

<%= render 'form', appoiment: @appoiment %>

<%= link_to 'Back', appoiments_path %>

konradtaller/app/views/appoiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consulting room:</strong>
  <%= @appoiment.consulting_room_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appoiment.patient_id %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appoiment.doctor_id %>
</p>

<p>
  <strong>Begindate:</strong>
  <%= @appoiment.begindate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @appoiment.enddate %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @appoiment.comment %>
</p>

<%= link_to 'Edit', edit_appoiment_path(@appoiment) %> |
<%= link_to 'Back', appoiments_path %>