konradtaller/config/routes.rb
Rails.application.routes.draw do
  resources :appoiments
  resources :consulting_rooms
  resources :doctors
  resources :professions
  resources :patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

konradtaller/app/models/profession.rb
class Profession < ApplicationRecord
end

konradtaller/app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :set_profession, only: [:show, :edit, :update, :destroy]

  # GET /professions
  # GET /professions.json
  def index
    @professions = Profession.all
  end

  # GET /professions/1
  # GET /professions/1.json
  def show
  end

  # GET /professions/new
  def new
    @profession = Profession.new
  end

  # GET /professions/1/edit
  def edit
  end

  # POST /professions
  # POST /professions.json
  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to @profession, notice: 'Profession was successfully created.' }
        format.json { render :show, status: :created, location: @profession }
      else
        format.html { render :new }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professions/1
  # PATCH/PUT /professions/1.json
  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to @profession, notice: 'Profession was successfully updated.' }
        format.json { render :show, status: :ok, location: @profession }
      else
        format.html { render :edit }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professions/1
  # DELETE /professions/1.json
  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: 'Profession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profession
      @profession = Profession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profession_params
      params.require(:profession).permit(:name)
    end
end

konradtaller/app/helpers/professions_helper.rb
module ProfessionsHelper
end

konradtaller/app/views/professions/_form.html.erb
<%= form_with(model: profession, local: true) do |form| %>
  <% if profession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profession.errors.count, "error") %> prohibited this profession from being saved:</h2>

      <ul>
        <% profession.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

konradtaller/app/views/professions/edit.html.erb
<h1>Editing Profession</h1>

<%= render 'form', profession: @profession %>

<%= link_to 'Show', @profession %> |
<%= link_to 'Back', professions_path %>

konradtaller/app/views/professions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professions.each do |profession| %>
      <tr>
        <td><%= profession.name %></td>
        <td><%= link_to 'Show', profession %></td>
        <td><%= link_to 'Edit', edit_profession_path(profession) %></td>
        <td><%= link_to 'Destroy', profession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profession', new_profession_path %>

konradtaller/app/views/professions/new.html.erb
<h1>New Profession</h1>

<%= render 'form', profession: @profession %>

<%= link_to 'Back', professions_path %>

konradtaller/app/views/professions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profession.name %>
</p>

<%= link_to 'Edit', edit_profession_path(@profession) %> |
<%= link_to 'Back', professions_path %>